In [100]:
import math
import numpy as np

In [106]:
# Constantes
Va = 24
Ra = 1.45
La = 454 * 10**-6
Rf = 75
Lf = 2
J = 0.0015
B = 0.098
Ia = 4
If = 1
Nrpm = 240

In [109]:
# Cálculos
𝜔m = Nrpm * math.pi / 30
Laf = (Va - Ia * Ra)/(If * 𝜔m)
Kφ = Laf * If
ea = Kφ * 𝜔m
Te = Kφ * Ia

print("𝜔m =", 𝜔m)
print("Laf =", Laf)
print("Kφ =", Kφ)
print("ea =", ea)
print("Te =", Te)

𝜔m = 25.13274122871834
Laf = 0.7241549910681239
Kφ = 0.7241549910681239
ea = 18.2
Te = 2.8966199642724955


In [111]:
# Matrizes
Ma = np.array([[-Ra/La, -Kφ/La], [Kφ/J, -B/J]])
Mb = np.array([[1/La, 0], [0, -1/J]])
Mc = np.array([[1, 0], [0, 1]])
Md = np.array([[0, 0], [0, 0]])

print("A:\n", Ma)
print("B:\n", Mb)
print("C:\n", Mc)
print("D:\n", Md)

A:
 [[-3193.83259912 -1595.05504641]
 [  482.76999405   -65.33333333]]
B:
 [[2202.64317181    0.        ]
 [   0.         -666.66666667]]
C:
 [[1 0]
 [0 1]]
D:
 [[0 0]
 [0 0]]
